version: '3'
services: 
  xrayr: 
    image: ghcr.io/hoshinoneko/xrayr:latest
    volumes:
      - ./config:/etc/XrayR/
      - /etc/nginx/ssl:/etc/XrayR/ssl
    restart: always
    network_mode: host
